/* Copyright 2026 Armel F4HWN
 * https://github.com/armel
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *     Unless required by applicable law or agreed to in writing, software
 *     distributed under the License is distributed on an "AS IS" BASIS,
 *     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *     See the License for the specific language governing permissions and
 *     limitations under the License.
 */

/*
 * APRS RX - receives APRS (AX.25 UI frames, Bell 202 AFSK 1200 bauds) in
 * software and shows the last frame: source, destination and path, the info
 * field. Tune the VFO (FM; 144.800 MHz, or 433.650 MHz for the Flipper Zero
 * bench files of test/flipper_aprs.py), then launch.
 *
 * The BK4829 has no Bell 202 demodulator (see README.md), so the RX audio is
 * sampled as EPIRB 406 does: it reaches PA4 (the voice DAC pin), held at
 * mid-scale by the MCU DAC (unbuffered), and is read on ADC channel 4 at
 * 9.6 kHz, timed from SysTick, continuously, as a TNC does: no RSSI gate, the
 * FCS and the UI check sort frames from noise. Each sample goes through the
 * demodulator modelled and tested in test/model_rx.py: band-pass, 1200/2200 Hz
 * sliding correlators over one bit, per-tone AGC, then 3 slicers (mark/space
 * weights 2:3, 1:1, 3:2), each with its DPLL, NRZI, HDLC and FCS. Keep the two
 * in step.
 * Keys and the screen cost sample time (the key scan alone is ~400 us), so they
 * are served every 50 ms only while no slicer is inside a preamble or a
 * plausible frame; the redraw follows a new frame, a key, or every 5 s.
 *
 * Keys (UV-K5 and UV-K1): 1 speaker on/off (off at launch: the decoder does
 *   not need it) · MENU clear · EXIT quit.
 * The loader re-runs RADIO_SetupRegisters on exit; the app restores the ADC,
 * PA4, the DAC and its clock itself.
 */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include "../app_api.h"
#include "aprsrx_assets.h"     /* generated by gen_assets.py */

/* ---- MCU registers (PY32F071, core and SysTick at 48 MHz, 10 ms period) ---- */
#define SYST_LOAD   (*(volatile uint32_t *)0xE000E014u)
#define SYST_VAL    (*(volatile uint32_t *)0xE000E018u)
#define ADC_SR      (*(volatile uint32_t *)0x40012400u)
#define ADC_CR2     (*(volatile uint32_t *)0x40012408u)
#define ADC_SMPR3   (*(volatile uint32_t *)0x40012414u)
#define ADC_SQR3    (*(volatile uint32_t *)0x40012438u)
#define ADC_DR      (*(volatile uint32_t *)0x40012450u)
#define GPIOA_MODER (*(volatile uint32_t *)0x50000000u)
#define DAC_CR      (*(volatile uint32_t *)0x40007400u)
#define DAC_SWTRIGR (*(volatile uint32_t *)0x40007404u)
#define DAC_DHR12R1 (*(volatile uint32_t *)0x40007408u)
#define RCC_APBENR1 (*(volatile uint32_t *)0x4002103Cu)
#define RCC_DACEN   (1u << 29)
/* DAC channel 1 on, output buffer off, software trigger (TSEL1 = 111) */
#define DAC_CR_BIAS ((1u << 0) | (1u << 1) | (1u << 2) | (7u << 3))
#define BIAS_CODE   2048u
#define ADC_SR_EOC     (1u << 1)
#define ADC_CR2_START  ((1u << 22) | (1u << 20))   /* SWSTART | EXTTRIG */
#define SMP8_POS       24u
#define SMP4_POS       12u
#define ADC_CH_PA4     4u
#define FS             9600u
#define CYC_PER_SAMPLE (48000000u / FS)            /* 5000 */
#define HOUSE_EVERY    480u    /* samples between key/screen slots (50 ms)       */
#define BUSY_MAX       60u     /* serve them anyway after 60 busy slots (3 s)    */
#define REFRESH_MS     5000u   /* periodic redraw (battery)                      */
#define DUP_MS         1000u   /* the same frame from another slicer             */

/* ---- BK4829 ---- */

/* ---- demodulator (test/model_rx.py, class Demod) ---- */
#define BP_B0       5356   /* band-pass 1625 Hz, Q 0.9, Q14 (b2 = -b0, b1 = 0) */
#define BP_A1     (-10714)
#define BP_A2       5673
#define AGC_ATT     5      /* peak tracker: attack 1/32 ...                 */
#define AGC_DEC     10     /* ... decay 1/1024 per sample                   */
#define PK_MIN      16
#define PLL_STEP    8192   /* 65536 per bit / 8 samples per bit             */
#define PLL_CTR     36864  /* transitions pulled to mid-bit + half a sample */
#define PLL_SHIFT   2      /* 1/4 of the error per transition               */
#define NSL         3      /* slicers                                       */
#define PRE_BITS    24u    /* busy for 3 bytes after two back-to-back flags */

/* ---- AX.25 ---- */
#define FRAME_MAX   330u   /* 10 addresses + control + PID + 256 info + FCS */
#define FRAME_MIN   18u    /* 2 addresses + control + PID + FCS              */
#define FCS_GOOD    0xF0B8u
#define COUNT_MAX   999u   /* counters stop here: the stats row stays within 32 tiny chars */

/* the front end shared by the slicers */
typedef struct {
    int32_t  dc;                       /* DC tracker, Q4                          */
    int32_t  x1, x2, y1, y2;           /* band-pass state                         */
    int32_t  im, qm, is, qs;           /* sliding correlator sums                 */
    int32_t  pm, ps;                   /* per-tone magnitude peaks (AGC)          */
    int16_t  ring[8][4];               /* the products of the last bit            */
    uint8_t  r, km, ks;                /* ring slot, table phases                 */
    int8_t   cm[8], cs[48];            /* cos tables (assets)                     */
} dem_t;

/* one slicer: decision weights, DPLL, NRZI, HDLC */
typedef struct {
    int32_t  dprev, phase;             /* last decision, DPLL phase (65536/bit)   */
    uint16_t n, crc;                   /* bytes, running FCS                      */
    uint8_t  wa, wb, last;             /* mark/space weights, last level          */
    uint8_t  sr, ones, byte, nb;       /* HDLC: shift reg, 1 run, byte, bit count */
    uint8_t  inframe, hdr;             /* between flags, first bytes look like a call */
    uint8_t  bits, pre;                /* bits since the last flag, back-to-back flags */
    uint8_t  buf[FRAME_MAX];
} sl_t;

/* The app state in one struct: a function loads one base address instead of one
 * literal-pool word per global. Words, then bytes, then halfwords, so every field
 * stays within the Thumb load/store immediate ranges (ldrb <= 31, ldrh <= 62,
 * ldr <= 124). The loader zeroes the overlay (.bss) at every launch. */
static struct {
    const app_api_t *A;
    uint8_t *frm;                      /* last good frame (app_main's stack)      */
    uint32_t vfoFreq;                  /* VFO RX frequency at launch, 10 Hz units */
    uint32_t tPrev, tCyc;              /* SysTick cycle counter                   */
    uint32_t tFrame, tDraw;            /* ticks_ms of the last frame, last redraw */
    uint32_t savedSqr3, savedSmpr3, savedModer, savedDac, savedRcc, savedDhr;
    uint8_t  seq, prevKey, redraw, spk; /* spk: speaker amplifier on (key 1)    */
    bool     running;
    int16_t  rssi;                     /* RSSI at the end of the last frame       */
    uint16_t flen, nOk;                /* frame length, frames                    */
} g;
static char str[34];

/* ---- tiny freestanding helpers: GCC may turn the zeroing / copy loops into calls ---- */
void *memset(void *d, int c, size_t n) {
    uint8_t *p = d; while (n--) *p++ = (uint8_t)c; return d;
}
void *memcpy(void *d, const void *s, size_t n) {
    uint8_t *p = d; const uint8_t *q = s; while (n--) *p++ = *q++; return d;
}

/* ---- formatting ---- */
static char *put(char *o,const char *s){ while(*s)*o++=*s++; return o; }
/* Formatting by repeated subtraction: no division. Values printed stay below 100000. */
static uint8_t sub(uint32_t *v,uint32_t d){ uint8_t q=0; while(*v>=d){ *v-=d; q++; } return q; }
static const uint16_t P10[]={10000u,1000u,100u,10u,1u};
static char *puti(char *o,int32_t v){
    uint32_t u;
    if(v<0){*o++='-';u=(uint32_t)(-v);} else u=(uint32_t)v;
    bool lead=false;
    for(uint8_t i=0;i<5;i++){
        uint8_t c=sub(&u,P10[i]);
        if(c||lead||i==4u){ *o++=(char)('0'+c); lead=true; }
    }
    return o;
}
/* A tiny row holds 32 characters (4 px each): print_tiny does not clip, so
 * every row built below stays within that. */
static void tiny(uint8_t y,char *end){ *end='\0'; g.A->print_tiny(str,0,y,false,true); }

#define WAIT_CAPS_X 40u    /* "WAIT" capsule in the status bar, after the title */
#define SPK_X       62u    /* speaker icon (FoxHunt's), after the capsule          */

/* Tiny rows under the source line: the path (capitals and digits: no
 * descenders), then 3 info rows 6 px apart (the 3x5 font is 5 px, 6 with
 * descenders), ending at y = 29 above the separator (y = 30). */
#define Y_PATH      8u
#define Y_INFO      13u
#define ROW_STEP    6u

/* The frequency (10 Hz units) drawn as the main screen draws it (ui/main.c,
 * ENABLE_BIG_FREQ): the big digits up to the kHz on lines 4-5, the last two
 * digits in the small font on line 5 right after them (from 1 GHz, the whole
 * string in the big font), the group centred. Big digits are 13 px (drawn from
 * +2), the point 3 px: the group shows (n big digits x 13 + 14) px. No division.
 * Same code as APRS TX. */
static void drawFreq(uint32_t f){
    const app_api_t *A=g.A;
    uint16_t m=0;
    while(f>=100000u){ f-=100000u; m++; }
    char *o=puti(str,m);
    *o++='.';
    for(uint8_t i=0;i<5u;i++) *o++=(char)('0'+sub(&f,P10[i]));
    *o='\0';
    uint8_t n=(uint8_t)(o-str), big=(uint8_t)(n-3u);    /* digits before "00" */
    if(m>=1000u){ A->print_string(str,(uint8_t)((128u-n*8u)>>1),0,4,8); return; }
    uint8_t x=(uint8_t)(((128u-(big*13u+14u))>>1)-2u);
    A->print_normal(str+n-2u,(uint8_t)(x+big*13u+3u),0,5);   /* "00"      */
    str[n-2u]='\0';
    A->display_freq(str,x,4,false);                          /* "144.800" */
}

/* ---- SysTick cycle counter (call at least every 10 ms; wraps every 89 s,
 * so compare with a signed difference) ---- */
static void clkStart(void){ g.tPrev=SYST_VAL; g.tCyc=0; }
static uint32_t clkCyc(void){
    uint32_t v=SYST_VAL;
    g.tCyc += (v<=g.tPrev) ? g.tPrev-v : g.tPrev+(SYST_LOAD+1u-v);
    g.tPrev=v;
    return g.tCyc;
}

/* ---- PA4 bias: the pin has no DC reference of its own (AC-coupled audio); the
 * MCU DAC on PA4, output buffer off, at mid-scale, holds it at ~VDD/2.
 * Set for the whole run, restored on exit (see EPIRB 406). ---- */
static void biasOn(void){
    GPIOA_MODER=g.savedModer|(3u<<8);           /* PA4 analog                     */
    RCC_APBENR1=g.savedRcc|RCC_DACEN;
    DAC_CR=DAC_CR_BIAS;
    DAC_DHR12R1=BIAS_CODE;
    DAC_SWTRIGR=1u;                           /* DHR -> DOR                     */
}
static void biasOff(void){ DAC_CR=g.savedDac; DAC_DHR12R1=g.savedDhr; RCC_APBENR1=g.savedRcc; GPIOA_MODER=g.savedModer; }

/* ---- ADC on PA4 (channel 4); channel 8 (battery) restored afterwards ---- */
static void adcSelPA4(void){
    ADC_SMPR3=(g.savedSmpr3&~(7u<<SMP4_POS))|(((g.savedSmpr3>>SMP8_POS)&7u)<<SMP4_POS);
    ADC_SQR3=(g.savedSqr3&~0x1Fu)|ADC_CH_PA4;
}
static void adcRestore(void){ ADC_SQR3=g.savedSqr3; ADC_SMPR3=g.savedSmpr3; }
static uint16_t adcRead(void){
    ADC_CR2|=ADC_CR2_START;
    for(uint16_t n=0; !(ADC_SR&ADC_SR_EOC) && n<2000u; n++){}
    return (uint16_t)(ADC_DR&0x0FFFu);
}

static bool callChar(uint8_t c){ return (c>='A'&&c<='Z')||(c>='0'&&c<='9')||c==' '; }

/* An APRS frame is a UI frame: the address field ends (bit 0 of an SSID byte)
 * and is followed by control 0x03 and PID 0xF0. Rejects the noise burst that
 * passes the 16-bit FCS about once a day in continuous decoding. */
static bool isUI(const uint8_t *f,uint16_t n){
    uint16_t end=(uint16_t)(n-2u), e=13;
    while(!(f[e]&1u) && e+7u<end) e+=7;
    return (f[e]&1u) && e+2u<end && f[e+1]==0x03u && f[e+2]==0xF0u;
}

/* ---- HDLC: one bit after NRZI. True when a UI frame with a good FCS just
 * ended (m->buf, m->n bytes, until the next byte). ---- */
static bool hdlcBit(sl_t *m,uint8_t b){
    if(m->bits<255u) m->bits++;
    m->sr=(uint8_t)((m->sr>>1)|(b<<7));
    if(m->sr==0x7Eu){
        bool ok = m->inframe && m->n>=FRAME_MIN && m->crc==FCS_GOOD && isUI(m->buf,m->n);
        m->pre = m->bits==8u ? (uint8_t)(m->pre<255u?m->pre+1u:255u) : 0;
        m->bits=0;
        if(ok) return true;                   /* n kept for the caller, reset below */
        m->inframe=1; m->hdr=1; m->n=0; m->crc=0xFFFFu;
        m->ones=m->byte=m->nb=0;
        return false;
    }
    if(b){
        if(++m->ones>6u){ m->ones=7; m->inframe=0; return false; }   /* abort / noise */
    } else {
        if(m->ones==5u){ m->ones=0; return false; }                 /* stuffed zero  */
        m->ones=0;
    }
    if(!m->inframe) return false;
    m->byte|=(uint8_t)(b<<m->nb);
    if(++m->nb==8u){
        if(m->n<FRAME_MAX){
            uint16_t c=m->crc^m->byte;        /* CRC-16/X.25, reflected 0x1021 */
            for(uint8_t i=0;i<8u;i++) c=(c&1u)?(uint16_t)((c>>1)^0x8408u):(uint16_t)(c>>1);
            m->crc=c;
            if(m->n<6u && ((m->byte&1u) || !callChar((uint8_t)(m->byte>>1)))) m->hdr=0;
            m->buf[m->n++]=m->byte;
        } else m->inframe=0;
        m->byte=m->nb=0;
    }
    return false;
}

/* A slicer is busy inside a preamble (two back-to-back flags, then 3 bytes) or
 * a frame whose first bytes look like a callsign: noise is busy ~4 % of the time. */
static bool busy(const sl_t *m){
    return (m->pre && m->bits<PRE_BITS) || (m->inframe && m->n && m->hdr);
}

/* |(i, q)| ~ max + 3/8 min */
static int32_t mag(int32_t i,int32_t q){
    if(i<0) i=-i;
    if(q<0) q=-q;
    if(i<q){ int32_t t=i; i=q; q=t; }
    return i+(q>>2)+(q>>3);
}

/* ---- front end, one ADC sample: *a = Mm*Ps, *b = Ms*Pm (each tone over its
 * own peak, without division; both stay below ~2^21) ---- */
static void front(dem_t *m,int32_t adc,int32_t *a,int32_t *b){
    m->dc+=((adc<<4)-m->dc)>>6;
    int32_t x=adc-(m->dc>>4);
    int32_t y=(BP_B0*(x-m->x2)-BP_A1*m->y1-BP_A2*m->y2)>>14;
    m->x2=m->x1; m->x1=x; m->y2=m->y1; m->y1=y;

    /* sliding correlators over one bit; the sine is the cos table 3/4 period ahead */
    int16_t *o=m->ring[m->r];
    uint8_t k=(uint8_t)(m->ks+12u); if(k>=48u) k-=48u;
    int32_t p;
    p=(y*m->cm[m->km])>>8;              m->im+=p-o[0]; o[0]=(int16_t)p;
    p=(y*m->cm[(m->km+6u)&7u])>>8;      m->qm+=p-o[1]; o[1]=(int16_t)p;
    p=(y*m->cs[m->ks])>>8;              m->is+=p-o[2]; o[2]=(int16_t)p;
    p=(y*m->cs[k])>>8;                  m->qs+=p-o[3]; o[3]=(int16_t)p;
    m->r=(uint8_t)((m->r+1u)&7u);
    m->km=(uint8_t)((m->km+1u)&7u);
    if(++m->ks>=48u) m->ks=0;

    int32_t mm=mag(m->im,m->qm), ms=mag(m->is,m->qs);
    m->pm+= mm>m->pm ? (mm-m->pm)>>AGC_ATT : -(m->pm>>AGC_DEC);
    m->ps+= ms>m->ps ? (ms-m->ps)>>AGC_ATT : -(m->ps>>AGC_DEC);
    if(m->pm<PK_MIN) m->pm=PK_MIN;
    if(m->ps<PK_MIN) m->ps=PK_MIN;
    *a=mm*m->ps;
    *b=ms*m->pm;
}

/* ---- slicer: decision sign(wa*a - wb*b), DPLL, NRZI, HDLC ---- */
static bool slice(sl_t *m,int32_t a,int32_t b){
    int32_t d=a*m->wa-b*m->wb;
    /* DPLL: a bit at each phase wrap (mid-bit), transitions pulled to mid-phase */
    m->phase+=PLL_STEP;
    if((d>0)!=(m->dprev>0)) m->phase+=(PLL_CTR-m->phase)>>PLL_SHIFT;
    m->dprev=d;
    if(m->phase>=65536){
        m->phase-=65536;
        uint8_t lv=d>0;
        bool r=hdlcBit(m,lv==m->last);    /* NRZI: no change = 1 */
        m->last=lv;
        return r;
    }
    return false;
}

/* ---- a good frame from a slicer: shown unless another slicer just gave it ---- */
static void accept(sl_t *m){
    const app_api_t *A=g.A;
    uint16_t n=m->n;
    uint32_t t=A->ticks_ms();
    if(!(n==g.flen && g.frm[n-1]==m->buf[n-1] && g.frm[n-2]==m->buf[n-2]
         && t-g.tFrame<DUP_MS)){
        memcpy(g.frm,m->buf,n);
        g.flen=n;
        if(g.nOk<COUNT_MAX) g.nOk++;
        g.seq++;
        g.rssi=A->rssi_dbm();              /* the carrier is still up: closing flags */
        g.redraw=1;
    }
    g.tFrame=t;
    m->inframe=1; m->hdr=1; m->n=0; m->crc=0xFFFFu;   /* this flag opens the next frame */
    m->ones=m->byte=m->nb=0;
}

/* ---- AX.25 address field -> "F4HWN-7" ---- */
static char *putCall(char *o,const uint8_t *a){
    for(uint8_t i=0;i<6u;i++){ char c=(char)(a[i]>>1); if(c!=' ') *o++=c; }
    uint8_t ssid=(uint8_t)((a[6]>>1)&15u);
    if(ssid){ *o++='-'; o=puti(o,ssid); }
    return o;
}

/* The tiny font covers 0x20-0x7F: anything else shows as '.'. */
static char safe(uint8_t ch){ return (ch<0x20u||ch>0x7Eu)?'.':(char)ch; }

/* Info bytes f[i..end) on one tiny row from o (up to 32 characters); returns
 * the next byte. */
static uint16_t textRow(char *o,const uint8_t *f,uint16_t i,uint16_t end,uint8_t y){
    for(; o<str+32 && i<end; i++) *o++=safe(f[i]);
    tiny(y,o);
    return i;
}

/* ---- Mic-E (APRS 1.0.1 chapter 10; test/mice.py is the reference) ----
 * The latitude, N/S, the longitude +100 offset, E/W and the message bits are in
 * the destination address; the longitude, speed, course and symbol in the info
 * field. Byte arithmetic wraps as uint8, so a bad field prints junk, never loops. */
static char *put2(char *o,uint32_t v){ *o++=(char)('0'+sub(&v,10u)); *o++=(char)('0'+v); return o; }
static char *put3(char *o,uint32_t v){ *o++=(char)('0'+sub(&v,100u)); return put2(o,v); }
static uint8_t micDigit(uint8_t c){
    if(c>='0'&&c<='9') return (uint8_t)(c-'0');
    if(c>='A'&&c<='J') return (uint8_t)(c-'A');
    if(c>='P'&&c<='Y') return (uint8_t)(c-'P');
    return 0;                                 /* K, L, Z: position ambiguity */
}
static bool micBit(uint8_t c){ return c>='P' || (c>='A'&&c<='K'); }
static bool micType(uint8_t t){ return t=='`'||t=='\''||t==0x1Cu||t==0x1Du; }

static void drawMicE(const uint8_t *f,uint16_t i,uint16_t end,const char *s){
    const app_api_t *A=g.A;
    uint8_t c[6];
    for(uint8_t k=0;k<6u;k++) c[k]=(uint8_t)(f[k]>>1);

    /* "48 50.89N 002 16.25E" */
    char *o=str;
    for(uint8_t k=0;k<6u;k++){
        *o++=(char)('0'+micDigit(c[k]));
        if(k==1u) *o++=' ';
        if(k==3u) *o++='.';
    }
    *o++=micBit(c[3])?'N':'S';
    uint32_t deg=(uint8_t)(f[i+1]-28u);
    if(micBit(c[4])) deg+=100u;
    if(deg>=180u && deg<=189u) deg-=80u;
    else if(deg>=190u && deg<=199u) deg-=190u;
    uint32_t mn=(uint8_t)(f[i+2]-28u);
    if(mn>=60u) mn-=60u;
    *o++=' '; o=put3(o,deg); *o++=' '; o=put2(o,mn); *o++='.'; o=put2(o,(uint8_t)(f[i+3]-28u));
    *o++=micBit(c[5])?'W':'E';
    tiny(Y_INFO,o);

    /* "12km/h 245 [/ En Route": speed in knots x 1.8525 (1897/1024) */
    uint32_t dc=(uint8_t)(f[i+5]-28u);
    uint32_t sp=(uint32_t)(uint8_t)(f[i+4]-28u)*10u+sub(&dc,10u);
    uint32_t crs=dc*100u+(uint8_t)(f[i+6]-28u);
    if(sp>=800u) sp-=800u;
    if(crs>=400u) crs-=400u;
    o=puti(str,(int32_t)((sp*1897u)>>10)); o=put(o,s+T_KMH);
    o=puti(o,(int32_t)crs); *o++=' ';
    *o++=safe(f[i+7]); *o++=safe(f[i+8]); *o++=' ';
    uint8_t idx=(uint8_t)(micBit(c[0])*4u+micBit(c[1])*2u+micBit(c[2]));
    bool custom=false;
    for(uint8_t k=0;k<3u;k++) if(c[k]>='A'&&c[k]<='K') custom=true;
    if(custom && idx){ o=put(o,s+T_CUSTOM); *o++=(char)('0'+7u-idx); }
    else o+=A->asset_read((uint16_t)(T_MSG+idx*T_MSG_STRIDE),o,T_MSG_STRIDE); /* NUL-padded */
    tiny(Y_INFO+ROW_STEP,o);

    /* comment: trailing CR/LF, the device markers (Yaesu/other: '`' or '\'' +
     * text + 2 chars; Kenwood: '>' or ']' + text [+ '=' or '^']) and a leading
     * "xxx}" altitude (base 91, metres + 10000) */
    uint16_t j=(uint16_t)(i+9u);
    while(end>j && (f[end-1]=='\r'||f[end-1]=='\n')) end--;
    if(j<end){
        uint8_t m=f[j];
        if(m=='`'||m=='\''){ j++; if(end-j>=2) end-=2u; }
        else if(m=='>'||m==']'){ j++; if(end>j && (f[end-1]=='='||f[end-1]=='^')) end--; }
    }
    o=str;
    if(end-j>=4 && f[j+3]=='}'){
        int32_t alt=(((int32_t)f[j]-33)*91+((int32_t)f[j+1]-33))*91+((int32_t)f[j+2]-33)-10000;
        o=puti(o,alt); *o++='m'; *o++=' ';
        j+=4u;
    }
    textRow(o,f,j,end,Y_INFO+2u*ROW_STEP);
}

/* ---- uncompressed position ('!' '=' or, after a 7-character timestamp, '/'
 * '@'; test/mice.py draw_pos is the reference): "49 21.07N 001 50.50E", then
 * the timestamp, the symbol and the comment. False for anything else (compressed
 * positions included), which is then shown as raw text. ---- */
static bool drawPos(const uint8_t *f,uint16_t i,uint16_t end){
    uint8_t t=f[i];
    uint16_t p=(uint16_t)(i+1u);
    if(t=='/'||t=='@') p+=7u;
    else if(t!='!'&&t!='=') return false;
    if(end<p+19u || f[p+4]!='.' || f[p+14]!='.') return false;
    const uint8_t *q=f+p;                     /* DDMM.hhN T DDDMM.hhE C */
    char *o=str;
    for(uint8_t k=0;k<18u;k++){
        if(k==8u) continue;                   /* symbol table: next row */
        if(k==2u||k==9u||k==12u) *o++=' ';
        *o++=safe(q[k]);
    }
    tiny(Y_INFO,o);
    o=str;
    if(p>i+1u){ for(uint16_t k=(uint16_t)(i+1u);k<p;k++) *o++=safe(f[k]); *o++=' '; }
    *o++=safe(q[8]); *o++=safe(q[18]); *o++=' ';
    textRow(str,f,textRow(o,f,(uint16_t)(p+19u),end,Y_INFO+ROW_STEP),end,Y_INFO+2u*ROW_STEP);
    return true;
}

/* ---- display ---- */
static void draw(void){
    const app_api_t *A=g.A;
    /* The UI texts live in the assets: one read per frame into this word-aligned
     * stack block, so each text costs a 2-byte sp-relative add instead of a
     * literal and its pool word (gen_assets.py keeps every offset aligned). */
    char s[UI_SIZE] __attribute__((aligned(4)));
    char *o;
    A->asset_read(0,s,UI_SIZE);
    A->display_clear();
    A->status_clear();
    A->print_inverse(s+T_TITLE,2,0,true,true,(uint8_t)(2u+T_TITLE_CHARS*4u));
    A->draw_battery();
    if(g.spk) A->asset_read(BMP_SPEAKER,A->status_line+SPK_X,BMP_SPEAKER_LEN);

    if(!g.flen)                          /* no frame yet: a capsule, as APRS TX's TRANSMIT */
        A->print_inverse(s+T_WAIT,WAIT_CAPS_X,0,true,true,(uint8_t)(WAIT_CAPS_X+T_WAIT_CHARS*4u));
    else {
        const uint8_t *f=g.frm;
        uint16_t end=(uint16_t)(g.flen-2u);    /* the FCS is not shown */

        o=putCall(str,f+7); *o++=' '; *o++='#'; o=puti(o,g.seq); *o='\0';
        A->print_normal(str,0,0,0);          /* source */

        /* ">DEST,DIGI*,..." while it fits one tiny row, then the rest of the
         * address field is skipped up to its end bit */
        o=str; *o++='>'; o=putCall(o,f);
        uint16_t e=13;                         /* SSID byte of the current address */
        while(!(f[e]&1u) && e+7u<end){
            e+=7;
            if(o<=str+20){ *o++=','; o=putCall(o,f+e-6); if(f[e]&0x80u) *o++='*'; }
        }
        tiny(Y_PATH,o);

        /* info field (after control and PID): Mic-E and uncompressed positions
         * decoded, anything else as text on 3 rows of 32 characters */
        uint16_t i=(uint16_t)(e+3u);
        if(end>=i+9u && micType(f[i])) drawMicE(f,i,end,s);
        else if(!drawPos(f,i,end))
            for(uint8_t row=0;row<3u;row++) i=textRow(str,f,i,end,(uint8_t)(Y_INFO+row*ROW_STEP));
    }

    /* dotted separator above the frequency: y = 30, bit 6 of line 3 (the big
     * digits start at y = 33) */
    for(uint8_t x=0;x<128u;x+=2u) A->fb[3][x]|=0x40u;
    drawFreq(g.vfoFreq);

    /* bottom line: "ok 12  -89dBm": frames, RSSI of the last one */
    o=put(str,s+T_OK); o=puti(o,g.nOk); *o++=' '; *o++=' ';
    o=puti(o,g.rssi); o=put(o,s+T_DBM);
    tiny(49,o);
}

/* ---- input ---- */
static void handleKeys(void){
    const app_api_t *A=g.A;
    uint8_t key=A->get_key();
    if(key==APP_KEY_INVALID||key==g.prevKey){ g.prevKey=key; return; }
    g.prevKey=key;
    g.redraw=1;
    if(key==APP_KEY_EXIT) g.running=false;
    else if(key==APP_KEY_MENU){ g.flen=0; g.nOk=0; g.seq=0; g.rssi=0; }
    else if(key==APP_KEY_1){ g.spk^=1u; A->audio_path(g.spk); }   /* speaker, as FoxHunt's audio */
}

/* ---- keys and screen, between frames ---- */
static void house(void){
    const app_api_t *A=g.A;
    handleKeys();
    if(!g.running) return;
    A->backlight_on();         /* keep the screen lit while listening */
    uint32_t t=A->ticks_ms();
    if(t-g.tDraw>=REFRESH_MS) g.redraw=1;
    if(!g.redraw) return;
    g.redraw=0;
    g.tDraw=t;
    adcRestore();                /* the battery is on ADC channel 8 */
    A->battery_sample();
    adcSelPA4();
    draw();
    A->blit_status();
    A->blit_full();
}

/* ---- the receiver: PA4 at 9.6 kHz, continuously, until EXIT ---- */
static void listen(void){
    const app_api_t *A=g.A;
    dem_t d;
    sl_t sl[NSL];
    memset(&d,0,sizeof d);
    memset(sl,0,sizeof sl);
    A->asset_read(COS1200,d.cm,COS1200_LEN);
    A->asset_read(COS2200,d.cs,COS2200_LEN);
    d.dc=(int32_t)BIAS_CODE<<4;
    d.pm=d.ps=64;
    sl[0].wa=2; sl[0].wb=3;      /* favours space */
    sl[1].wa=1; sl[1].wb=1;
    sl[2].wa=3; sl[2].wb=2;      /* favours mark  */
    for(uint8_t k=0;k<NSL;k++) sl[k].crc=0xFFFFu;

    adcSelPA4();
    clkStart();
    uint32_t next=CYC_PER_SAMPLE;
    uint16_t cnt=0;
    uint8_t busyFor=0;
    g.redraw=1;
    while(g.running){
        while((int32_t)(clkCyc()-next)<0){}
        next+=CYC_PER_SAMPLE;
        int32_t a,b;
        front(&d,adcRead(),&a,&b);
        bool bz=false;
        for(uint8_t k=0;k<NSL;k++){
            if(slice(&sl[k],a,b)) accept(&sl[k]);
            bz|=busy(&sl[k]);
        }
        if(++cnt<HOUSE_EVERY) continue;
        cnt=0;
        if(bz && ++busyFor<BUSY_MAX) continue;
        busyFor=0;
        house();
        next=clkCyc()+CYC_PER_SAMPLE;   /* skip the samples the slot took */
    }
    adcRestore();
}

__attribute__((section(".text.entry"),used))
void app_main(const app_api_t *api){
    uint8_t frm[FRAME_MAX];      /* on the stack: the 4 KiB overlay also holds .bss */
    g.A=api;
    g.frm=frm;
    g.prevKey=APP_KEY_INVALID;   /* the rest of g starts at 0 (overlay zeroed by the loader) */

    g.savedSqr3=ADC_SQR3; g.savedSmpr3=ADC_SMPR3; g.savedModer=GPIOA_MODER; g.savedDac=DAC_CR;
    g.savedRcc=RCC_APBENR1; g.savedDhr=DAC_DHR12R1;
    biasOn();
    api->backlight_on();
    g.vfoFreq=api->rx_freq();
    /* Speaker amplifier (PA8) off: the decoder does not need it (tested on the
     * radio, 2026-09-30): PA4, the voice-prompt DAC pin, joins the audio before
     * the amplifier; only the BK4829 AF output must be on. Key 1 turns the
     * speaker on to listen to the channel. */
    api->audio_path(false);
    api->set_af(APP_AF_FM);
    api->delay_ms(50);

    g.running=true;
    listen();

    biasOff();
    api->set_af(APP_AF_MUTE);
    api->audio_path(false);
}
